site_name: REA Automation System Design
dev_addr: 127.0.0.1:3030

theme:
  name: material
  features:
    - navigation.tracking

markdown_extensions:
  - def_list
  - pymdownx.superfences

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Getting Started: getting-started/index.md
  - How to Create a Node: how-to-create-node/index.md
  - Timeline Estimation: timeline-estimation/index.md